/**
 * Claude Code config generator
 *
 * Generates:
 *   - CLAUDE.md                    (repo root — primary instruction file)
 *   - .claude/settings.json        (shared team permissions — commit to git)
 *   - .claude/commands/*.md        (thin wrappers → .agent/workflows/)
 *   - .claude/agents/{agent}.md    (thin wrappers with subagent frontmatter → .agent/agents/)
 *   - .mcp.json                    (project-scoped MCP config)
 *
 * .claude/ contains ZERO content — only 3-line pointer wrappers.
 * .agent/ is the single source of truth. Run `studio sync` after editing agents.
 */

import fs from "fs-extra";
import path from "path";
import { logger } from "../../ui/logger.js";
import { composeMcp } from "../mcp-composer.js";
import {
  TEMPLATES_DIR,
  buildTemplateCtx,
  parseFrontmatter,
  writeFromTemplate,
  type IdeConfigContext,
} from "./types.js";

export function generateClaudeConfig(cwd: string, ctx: IdeConfigContext): void {
  const { selectedAgents, force = false } = ctx;

  logger.step("Configuring Claude Code...");

  // 1. CLAUDE.md at repo root — primary Claude Code instruction file
  writeFromTemplate(
    path.join(TEMPLATES_DIR, ".claude", "CLAUDE.md"),
    path.join(cwd, "CLAUDE.md"),
    buildTemplateCtx(ctx),
    "CLAUDE.md",
    force
  );

  // 2. .claude/settings.json — shared team permissions (safe to commit)
  const settingsPath = path.join(cwd, ".claude", "settings.json");
  if (force || !fs.existsSync(settingsPath)) {
    fs.ensureDirSync(path.dirname(settingsPath));
    const settings = {
      $schema: "https://json.schemastore.org/claude-code-settings.json",
      permissions: {
        allow: [
          "Bash(npm run *)",
          "Bash(npx *)",
          "Bash(pnpm *)",
          "Bash(node *)",
          "Bash(git *)",
          "Bash(tsc *)",
        ],
        deny: [
          "Read(./.env)",
          "Read(./.env.*)",
          "Read(./secrets/**)",
          "Read(**/*.pem)",
          "Read(**/*.key)",
        ],
      },
    };
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
    logger.success(".claude/settings.json");
  } else {
    logger.dim("Skipped .claude/settings.json (already exists)");
  }

  // 3. .claude/commands/ — thin wrappers pointing to .agent/workflows/
  // .agent/workflows/ is the source of truth — never copy content here.
  // Claude reads the wrapper and follows the path reference to get full content.
  const commandsDir = path.join(cwd, ".claude", "commands");
  fs.ensureDirSync(commandsDir);
  const workflowsDir = path.join(cwd, ".agent", "workflows");
  let commandCount = 0;
  if (fs.existsSync(workflowsDir)) {
    for (const file of fs.readdirSync(workflowsDir).filter((f) => f.endsWith(".md"))) {
      const destPath = path.join(commandsDir, file);
      if (!force && fs.existsSync(destPath)) continue;
      const wrapper = [
        `<!-- Auto-generated by studio init — DO NOT EDIT -->`,
        `<!-- Source of truth: .agent/workflows/${file} -->`,
        `<!-- Regenerate: studio sync -->`,
        ``,
        `Read and execute the full workflow defined in \`.agent/workflows/${file}\`.`,
      ].join("\n") + "\n";
      fs.writeFileSync(destPath, wrapper, "utf8");
      commandCount++;
    }
  }
  if (commandCount > 0) {
    logger.success(`.claude/commands/ — ${commandCount} thin wrappers → .agent/workflows/`);
  }

  // 4. .claude/agents/ — thin wrappers with Claude subagent frontmatter pointing to .agent/agents/
  // Only the YAML frontmatter (name/description/tools) is generated here so Claude
  // can discover and activate subagents. The body is a single pointer — no content duplication.
  // .agent/agents/ is the source of truth. Run `studio sync` after adding/editing agents.
  const claudeAgentsDir = path.join(cwd, ".claude", "agents");
  fs.ensureDirSync(claudeAgentsDir);
  let subagentCount = 0;
  for (const agentId of selectedAgents) {
    const srcPath = path.join(cwd, ".agent", "agents", `${agentId}.md`);
    if (!fs.existsSync(srcPath)) continue;
    const destPath = path.join(claudeAgentsDir, `${agentId}.md`);
    if (!force && fs.existsSync(destPath)) continue;

    // Read description from source frontmatter only — never copy the body
    const content = fs.readFileSync(srcPath, "utf8");
    const { data: agentMeta } = parseFrontmatter(content);
    const description =
      agentMeta.description ??
      `${agentId.replace(/-/g, " ")} specialist — activate for related tasks`;

    // Thin wrapper: Claude subagent discovery frontmatter + pointer body only
    const wrapper = [
      "---",
      `name: ${agentId}`,
      `description: ${description}`,
      "tools:",
      "  - Read",
      "  - Write",
      "  - Bash",
      "---",
      "",
      `<!-- Auto-generated by studio init — DO NOT EDIT -->`,
      `<!-- Source of truth: .agent/agents/${agentId}.md -->`,
      `<!-- Regenerate: studio sync -->`,
      ``,
      `Read and fully apply the agent definition in \`.agent/agents/${agentId}.md\`.`,
    ].join("\n") + "\n";
    fs.writeFileSync(destPath, wrapper, "utf8");
    subagentCount++;
  }
  if (subagentCount > 0) {
    logger.success(`.claude/agents/ — ${subagentCount} thin wrappers → .agent/agents/`);
  }

  // 5. .mcp.json — project-scoped MCP config (mcpServers key, no type field)
  composeMcp(
    cwd,
    "claude",
    ctx.profile,
    path.join(cwd, ".mcp.json"),
    ".mcp.json",
    force
  );
}
