/**
 * `studio ci [--platform github|gitlab] [--force]`
 *
 * Generates a CI pipeline configuration that runs `studio validate` on every
 * push / pull-request, ensuring the enterprise quality gates are enforced in CI.
 *
 * Supported platforms:
 *   github  → .github/workflows/studio-validate.yml
 *   gitlab  → .gitlab-ci.yml  (studio job appended)
 */

import * as p from "@clack/prompts";
import fs from "fs-extra";
import path from "path";
import chalk from "chalk";
import gradient from "gradient-string";
import { readConfig } from "../core/config-manager.js";
import { detectProject } from "../core/project-detector.js";
import { logger } from "../ui/logger.js";

export type CiPlatform = "github" | "gitlab";

export interface CiOptions {
  platform?: CiPlatform;
  force?: boolean;
}

export async function ciCommand(cwd: string, opts: CiOptions = {}): Promise<void> {
  const config      = readConfig(cwd);
  const projectInfo = detectProject(cwd);
  const cyanPink    = gradient(["#00DBDE", "#FC00FF"]);

  logger.blank();
  process.stdout.write(cyanPink.multiline(`  Nexus CI Generator\n  ${"─".repeat(35)}\n`));

  // ── Detect or prompt for platform ─────────────────────────────────────────
  let platform: CiPlatform;

  if (opts.platform) {
    platform = opts.platform;
  } else {
    // Auto-detect
    const hasGithub = fs.existsSync(path.join(cwd, ".github"));
    const hasGitlab = fs.existsSync(path.join(cwd, ".gitlab-ci.yml"));

    if (hasGithub && !hasGitlab) {
      platform = "github";
      logger.dim("Auto-detected: GitHub Actions");
    } else if (hasGitlab && !hasGithub) {
      platform = "gitlab";
      logger.dim("Auto-detected: GitLab CI");
    } else {
      const choice = await p.select({
        message: "Which CI platform?",
        options: [
          { value: "github", label: "GitHub Actions", hint: ".github/workflows/studio-validate.yml" },
          { value: "gitlab", label: "GitLab CI",      hint: ".gitlab-ci.yml" },
        ],
      });
      if (p.isCancel(choice)) { logger.info("Cancelled."); return; }
      platform = choice as CiPlatform;
    }
  }

  // ── Determine Node version ────────────────────────────────────────────────
  const nodeVersion = process.version.slice(1).split(".")[0] ?? "20";

  if (platform === "github") {
    await _generateGitHubActions(cwd, nodeVersion, projectInfo.framework.language, opts.force ?? false);
  } else {
    await _generateGitLabCi(cwd, nodeVersion, opts.force ?? false);
  }
}

// ── GitHub Actions ────────────────────────────────────────────────────────────

async function _generateGitHubActions(
  cwd: string,
  nodeVersion: string,
  language: string,
  force: boolean
): Promise<void> {
  const workflowDir  = path.join(cwd, ".github", "workflows");
  const workflowPath = path.join(workflowDir, "studio-validate.yml");

  if (fs.existsSync(workflowPath) && !force) {
    logger.warn(`${workflowPath} already exists. Use --force to overwrite.`);
    return;
  }

  const setupStep = _languageSetupStep(language, nodeVersion);

  const yaml = `# Generated by Nexus Studio — studio ci
# Runs enterprise quality gates on every push and pull request.
# Edit this file to customise triggers, environment, or add steps.

name: Nexus Studio — Quality Gates

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

${setupStep}
      - name: Install dependencies
        run: ${_installCommand(language)}

      - name: Install Nexus Studio CLI
        run: npm install -g @antigravity/studio

      - name: Validate — Nexus Quality Gates
        run: studio validate

      - name: Sync check — detect template drift
        run: studio sync --check
`;

  await fs.ensureDir(workflowDir);
  await fs.writeFile(workflowPath, yaml, "utf8");

  logger.success(`Created .github/workflows/studio-validate.yml`);
  logger.blank();
  logger.box(
    `${chalk.bold.white("GitHub Actions CI ready!")}\n\n` +
    `  Commit ${chalk.cyan(".github/workflows/studio-validate.yml")} to enable.\n\n` +
    `  ${chalk.dim("Triggers:")} push + pull_request on main/master/develop\n` +
    `  ${chalk.dim("Checks:")}   studio validate + studio sync --check`,
    { borderColor: "green", padding: 1, margin: { top: 1, bottom: 1 } }
  );
}

// ── GitLab CI ─────────────────────────────────────────────────────────────────

async function _generateGitLabCi(cwd: string, nodeVersion: string, force: boolean): Promise<void> {
  const gitlabPath = path.join(cwd, ".gitlab-ci.yml");
  const jobBlock   = `
# ── Nexus Studio Quality Gates (generated by studio ci) ──────────────────────
studio-quality-gates:
  stage: test
  image: node:${nodeVersion}-alpine
  before_script:
    - npm ci
    - npm install -g @antigravity/studio
  script:
    - studio validate
    - studio sync --check
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`;

  if (fs.existsSync(gitlabPath) && !force) {
    // Append job block to existing file
    const existing = await fs.readFile(gitlabPath, "utf8");
    if (existing.includes("studio-quality-gates")) {
      logger.warn(".gitlab-ci.yml already contains a studio-quality-gates job. Use --force to overwrite.");
      return;
    }
    await fs.writeFile(gitlabPath, existing + jobBlock, "utf8");
    logger.success(`Appended studio-quality-gates job to .gitlab-ci.yml`);
  } else {
    const baseYaml = `# Generated by Nexus Studio — studio ci\nstages:\n  - test\n${jobBlock}`;
    await fs.writeFile(gitlabPath, baseYaml, "utf8");
    logger.success(`Created .gitlab-ci.yml`);
  }

  logger.blank();
  logger.box(
    `${chalk.bold.white("GitLab CI ready!")}\n\n` +
    `  Commit ${chalk.cyan(".gitlab-ci.yml")} to enable.\n\n` +
    `  ${chalk.dim("Checks:")} studio validate + studio sync --check`,
    { borderColor: "green", padding: 1, margin: { top: 1, bottom: 1 } }
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function _languageSetupStep(language: string, nodeVersion: string): string {
  if (language === "python") {
    return `      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"\n`;
  }
  if (language === "java") {
    return `      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"\n`;
  }
  if (language === "csharp") {
    return `      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"\n`;
  }
  // Default: Node.js
  return `      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${nodeVersion}"
          cache: "npm"\n`;
}

function _installCommand(language: string): string {
  if (language === "python") return "pip install -r requirements.txt";
  if (language === "java")   return "mvn install -q -DskipTests";
  if (language === "csharp") return "dotnet restore";
  return "npm ci";
}
