/**
 * `studio completion [shell]`
 *
 * Outputs a shell completion script for bash, zsh, fish, or PowerShell.
 *
 * Usage:
 *   studio completion bash   >> ~/.bash_completion.d/studio
 *   studio completion zsh    >> ~/.zshrc
 *   studio completion fish   > ~/.config/fish/completions/studio.fish
 *   studio completion pwsh   >> $PROFILE
 *
 * Or run interactively (no shell arg) to see instructions.
 */

import { logger } from "../ui/logger.js";
import chalk from "chalk";
import gradient from "gradient-string";
import boxen from "boxen";

const COMMANDS = [
  "init", "status", "list", "search", "info", "diff",
  "add", "remove", "update", "sync", "rollback",
  "validate", "run", "doctor", "ci", "create",
  "company", "mcp", "completion",
];

const ADD_TYPES   = ["agent", "skill", "workflow", "script"];
const MCP_SUBS    = ["list", "add", "remove", "apply"];
const COMPANY_SUBS = ["init", "validate"];
const STACKS      = ["node", "python", "java", "dotnet", "flutter"];
const CI_PLATFORMS = ["github", "gitlab"];
const SHELLS      = ["bash", "zsh", "fish", "pwsh"] as const;
type Shell = typeof SHELLS[number];

export async function completionCommand(shell: string | undefined): Promise<void> {
  if (!shell) {
    _printInstructions();
    return;
  }

  if (!SHELLS.includes(shell as Shell)) {
    logger.error(`Unknown shell "${shell}". Supported: ${SHELLS.join(", ")}`);
    process.exit(1);
  }

  const script = _generateScript(shell as Shell);
  process.stdout.write(script);
}

// ── Instruction printer ───────────────────────────────────────────────────────

function _printInstructions(): void {
  const cyanPink = gradient(["#00DBDE", "#FC00FF"]);
  logger.blank();
  process.stdout.write(cyanPink.multiline(`  Nexus Studio — Shell Completion\n  ${"─".repeat(40)}\n`));

  console.log(
    boxen(
      `${chalk.bold("Install tab completion for your shell:")}\n\n` +

      `  ${chalk.bold.white("Bash")} (add to ~/.bashrc):\n` +
      `  ${chalk.cyan('eval "$(studio completion bash)"')}\n\n` +

      `  ${chalk.bold.white("Zsh")} (add to ~/.zshrc):\n` +
      `  ${chalk.cyan('eval "$(studio completion zsh)"')}\n\n` +

      `  ${chalk.bold.white("Fish")}:\n` +
      `  ${chalk.cyan("studio completion fish > ~/.config/fish/completions/studio.fish")}\n\n` +

      `  ${chalk.bold.white("PowerShell")} (add to $PROFILE):\n` +
      `  ${chalk.cyan('Invoke-Expression (& studio completion pwsh)')}`,
      { padding: 1, margin: { top: 0, bottom: 1 }, borderStyle: "round", borderColor: "cyan" }
    )
  );
}

// ── Script generators ─────────────────────────────────────────────────────────

function _generateScript(shell: Shell): string {
  switch (shell) {
    case "bash": return _bash();
    case "zsh":  return _zsh();
    case "fish": return _fish();
    case "pwsh": return _pwsh();
  }
}

function _bash(): string {
  const cmds    = COMMANDS.join(" ");
  const types   = ADD_TYPES.join(" ");
  const stacks  = STACKS.join(" ");
  const mcpSubs = MCP_SUBS.join(" ");
  const coSubs  = COMPANY_SUBS.join(" ");
  const ciPlat  = CI_PLATFORMS.join(" ");

  return `# Nexus Studio bash completion
# Generated by: studio completion bash
_studio_completion() {
  local cur prev words
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  words="\${COMP_WORDS[*]}"

  case "\${prev}" in
    studio)
      COMPREPLY=($(compgen -W "${cmds}" -- "\${cur}"))
      return ;;
    add|remove)
      COMPREPLY=($(compgen -W "${types}" -- "\${cur}"))
      return ;;
    mcp)
      COMPREPLY=($(compgen -W "${mcpSubs}" -- "\${cur}"))
      return ;;
    company)
      COMPREPLY=($(compgen -W "${coSubs}" -- "\${cur}"))
      return ;;
    completion)
      COMPREPLY=($(compgen -W "bash zsh fish pwsh" -- "\${cur}"))
      return ;;
    ci)
      COMPREPLY=($(compgen -W "${ciPlat}" -- "\${cur}"))
      return ;;
    --stack|-s)
      COMPREPLY=($(compgen -W "${stacks}" -- "\${cur}"))
      return ;;
    create)
      COMPREPLY=($(compgen -W "agent skill workflow" -- "\${cur}"))
      return ;;
    info|diff)
      COMPREPLY=($(compgen -W "agent skill workflow" -- "\${cur}"))
      return ;;
  esac

  # Handle flags
  if [[ "\${cur}" == -* ]]; then
    COMPREPLY=($(compgen -W "--help --version --debug --force --dry-run --fix --check --all --stack --type --platform --list --quiet" -- "\${cur}"))
  fi
}

complete -F _studio_completion studio
`;
}

function _zsh(): string {
  const cmds  = COMMANDS.map((c) => `'${c}'`).join(" ");
  const types = ADD_TYPES.map((t) => `'${t}'`).join(" ");
  return `# Nexus Studio zsh completion
# Generated by: studio completion zsh
_studio() {
  local context state state_descr line
  typeset -A opt_args

  _arguments \\
    '1: :->command' \\
    '*: :->args'

  case \$state in
    command)
      _values 'commands' ${cmds}
      ;;
    args)
      case \$line[1] in
        add|remove)   _values 'types' ${types} ;;
        mcp)          _values 'mcp subcommands' ${MCP_SUBS.map((s) => `'${s}'`).join(" ")} ;;
        company)      _values 'company subcommands' ${COMPANY_SUBS.map((s) => `'${s}'`).join(" ")} ;;
        completion)   _values 'shells' 'bash' 'zsh' 'fish' 'pwsh' ;;
        ci)           _values 'platforms' 'github' 'gitlab' ;;
        create|info|diff) _values 'types' 'agent' 'skill' 'workflow' ;;
      esac
      ;;
  esac
}

compdef _studio studio
`;
}

function _fish(): string {
  const cmdLines = COMMANDS.map(
    (c) => `complete -c studio -f -n '__fish_use_subcommand' -a ${c}`
  ).join("\n");

  return `# Nexus Studio fish completion
# Generated by: studio completion fish

function __fish_use_subcommand
  set -l cmd (commandline -poc)
  if test (count \$cmd) -eq 1
    return 0
  end
  return 1
end

${cmdLines}

# add / remove sub-types
${ADD_TYPES.map((t) => `complete -c studio -f -n '__fish_seen_subcommand_from add remove' -a ${t}`).join("\n")}

# mcp sub-commands
${MCP_SUBS.map((s) => `complete -c studio -f -n '__fish_seen_subcommand_from mcp' -a ${s}`).join("\n")}

# company sub-commands
${COMPANY_SUBS.map((s) => `complete -c studio -f -n '__fish_seen_subcommand_from company' -a ${s}`).join("\n")}

# ci platforms
${CI_PLATFORMS.map((p) => `complete -c studio -f -n '__fish_seen_subcommand_from ci' -a ${p}`).join("\n")}

# completion shells
complete -c studio -f -n '__fish_seen_subcommand_from completion' -a bash
complete -c studio -f -n '__fish_seen_subcommand_from completion' -a zsh
complete -c studio -f -n '__fish_seen_subcommand_from completion' -a fish
complete -c studio -f -n '__fish_seen_subcommand_from completion' -a pwsh

# --stack flag
${STACKS.map((s) => `complete -c studio -l stack -f -a ${s}`).join("\n")}
`;
}

function _pwsh(): string {
  const cmdsArr = COMMANDS.map((c) => `'${c}'`).join(", ");
  return `# Nexus Studio PowerShell completion
# Generated by: studio completion pwsh
# Add to your $PROFILE: Invoke-Expression (& studio completion pwsh)

Register-ArgumentCompleter -Native -CommandName studio -ScriptBlock {
  param(\$wordToComplete, \$commandAst, \$cursorPosition)

  \$commands = @(${cmdsArr})
  \$types    = @('agent', 'skill', 'workflow', 'script')
  \$stacks   = @(${STACKS.map((s) => `'${s}'`).join(", ")})
  \$mcpSubs  = @(${MCP_SUBS.map((s) => `'${s}'`).join(", ")})
  \$coSubs   = @(${COMPANY_SUBS.map((s) => `'${s}'`).join(", ")})

  \$tokens = \$commandAst.CommandElements
  \$prev   = if (\$tokens.Count -gt 1) { \$tokens[\$tokens.Count - 2].Value } else { '' }

  \$completions = switch (\$prev) {
    'studio'   { \$commands }
    { 'add','remove' -contains \$_ } { \$types }
    'mcp'      { \$mcpSubs }
    'company'  { \$coSubs }
    'completion' { @('bash','zsh','fish','pwsh') }
    'ci'       { @('github','gitlab') }
    { 'create','info','diff' -contains \$_ } { @('agent','skill','workflow') }
    '--stack'  { \$stacks }
    default    { @() }
  }

  \$completions | Where-Object { \$_ -like "\$wordToComplete*" } |
    ForEach-Object { [System.Management.Automation.CompletionResult]::new(\$_, \$_, 'ParameterValue', \$_) }
}
`;
}
