/**
 * Profile Manager — Manages the developer's global profile at ~/.agstudio/profile.md
 *
 * The profile is the DEVELOPER LAYER of the context system:
 *   - Stored globally at ~/.agstudio/profile.md (persists across all projects)
 *   - Injected into .agent/context/DEVELOPER.md in each project by `studio context init/sync`
 *   - Read by the AI to adapt tone, verbosity, and pattern suggestions
 *
 * File location:
 *   Windows:   C:\Users\<user>\.agstudio\profile.md
 *   Mac/Linux: /home/<user>/.agstudio/profile.md
 */

import fs from "fs-extra";
import path from "path";
import os from "os";

// ─── Constants ────────────────────────────────────────────────────────────────

export const AGSTUDIO_GLOBAL_DIR = path.join(os.homedir(), ".agstudio");
export const PROFILE_PATH = path.join(AGSTUDIO_GLOBAL_DIR, "profile.md");

// ─── Types ────────────────────────────────────────────────────────────────────

export interface DeveloperSkill {
  name: string;
  level: number; // 1–10
  category: string;
}

export interface DeveloperProfile {
  name: string;
  role: string;
  company: string;
  skills: DeveloperSkill[];
  verbosity: "concise" | "standard" | "detailed";
  codeFirst: boolean;             // true = show code first, then explain
  preferredPatterns: string[];
  learningFocus: string[];
  createdAt: string;
  updatedAt: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns true if ~/.agstudio/profile.md exists */
export function profileExists(): boolean {
  return fs.existsSync(PROFILE_PATH);
}

/** Returns the profile file path */
export function getProfilePath(): string {
  return PROFILE_PATH;
}

/**
 * Compute a short SHA-256 hash of the profile file content.
 * Used by `studio context sync` to detect if profile changed since last inject.
 */
export async function getProfileHash(): Promise<string | null> {
  if (!profileExists()) return null;
  const { createHash } = await import("crypto");
  const content = fs.readFileSync(PROFILE_PATH, "utf-8");
  return createHash("sha256").update(content).digest("hex").slice(0, 12);
}

// ─── Read ─────────────────────────────────────────────────────────────────────

/** Read the raw markdown content of the profile file */
export function readProfileRaw(): string | null {
  if (!profileExists()) return null;
  return fs.readFileSync(PROFILE_PATH, "utf-8");
}

// ─── Write ────────────────────────────────────────────────────────────────────

/** Write a fully rendered profile markdown string to ~/.agstudio/profile.md */
export function writeProfile(content: string): void {
  fs.ensureDirSync(AGSTUDIO_GLOBAL_DIR);
  fs.writeFileSync(PROFILE_PATH, content, "utf-8");
}

// ─── Render ───────────────────────────────────────────────────────────────────

/**
 * Render a DeveloperProfile object into the standard markdown format.
 * This is the canonical profile format — DEVELOPER.md in each project
 * is populated with this exact content.
 */
export function renderProfile(profile: DeveloperProfile): string {
  const skillsByCategory = profile.skills.reduce<Record<string, DeveloperSkill[]>>(
    (acc, skill) => {
      if (!acc[skill.category]) acc[skill.category] = [];
      acc[skill.category]!.push(skill);
      return acc;
    },
    {}
  );

  const skillTable = Object.entries(skillsByCategory)
    .map(([category, skills]) => {
      const rows = skills
        .sort((a, b) => b.level - a.level)
        .map((s) => {
          const bar = "█".repeat(Math.round(s.level / 2)) + "░".repeat(5 - Math.round(s.level / 2));
          const aiNote =
            s.level >= 8
              ? "Skip basics — use advanced patterns"
              : s.level >= 5
              ? "Intermediate — some context helpful"
              : "Learning — add explanations & safer alternatives";
          return `| ${s.name} | ${s.level}/10 ${bar} | ${aiNote} |`;
        })
        .join("\n");
      return `### ${category}\n\n| Skill | Level | AI Behavior |\n|-------|-------|-------------|\n${rows}`;
    })
    .join("\n\n");

  const patterns =
    profile.preferredPatterns.length > 0
      ? profile.preferredPatterns.map((p) => `- ${p}`).join("\n")
      : "- _(not configured)_";

  const learning =
    profile.learningFocus.length > 0
      ? profile.learningFocus.map((l) => `- ${l} ← provide more context & explanations here`).join("\n")
      : "- _(none specified)_";

  return `# Developer Profile
<!-- ──────────────────────────────────────────────────────────────────────────
  This file is AUTO-INJECTED by Nexus Studio from ~/.agstudio/profile.md
  DO NOT edit this file directly — your changes will be overwritten on sync.

  To update: edit ~/.agstudio/profile.md then run \`studio context sync\`
  To edit your profile: run \`studio profile edit\`
──────────────────────────────────────────────────────────────────────────── -->

> **AI Instruction**: Read this file before every response. Adapt your tone,
> verbosity, and explanation depth to match this developer's expertise profile.

## Identity

| Property | Value |
|----------|-------|
| **Name** | ${profile.name} |
| **Role** | ${profile.role} |
| **Company** | ${profile.company} |
| **Profile updated** | ${profile.updatedAt} |

## Communication Preferences

| Preference | Setting | Meaning |
|-----------|---------|---------|
| **Verbosity** | ${profile.verbosity} | ${profile.verbosity === "concise" ? "Keep responses short and direct" : profile.verbosity === "detailed" ? "Full explanations always welcome" : "Balance code and explanation"} |
| **Style** | ${profile.codeFirst ? "Code first" : "Explain first"} | ${profile.codeFirst ? "Show code immediately, explain after" : "Explain approach, then show code"} |

## Skill Levels

> Scale: 1–10 | █████ = 10 | AI skips basics for skills ≥ 8

${skillTable}

## Preferred Patterns

${patterns}

## Learning Focus

> Provide extra context and explanations for these areas:

${learning}

---

*Managed by Nexus Studio · Edit with \`studio profile edit\` · Sync with \`studio context sync\`*
`;
}
